package przelewy24

const (
	// These are the languages allowed by P24 documentation.
	LanguageBG Language = "bg"
	LanguageCS Language = "cs"
	LanguageDE Language = "de"
	LanguageEN Language = "en"
	LanguageES Language = "es"
	LanguageFR Language = "fr"
	LanguageHR Language = "hr"
	LanguageHU Language = "hu"
	LanguageIT Language = "it"
	LanguageNL Language = "nl"
	LanguagePL Language = "pl"
	LanguagePT Language = "pt"
	LanguageSE Language = "se"
	LanguageSK Language = "sk"
	LanguageRO Language = "ro"

	CountryAD Country = "AD"
	CountryAT Country = "AT"
	CountryBE Country = "BE"
	CountryBG Country = "BG"
	CountryCH Country = "CH"
	CountryCY Country = "CY"
	CountryCZ Country = "CZ"
	CountryDE Country = "DE"
	CountryDK Country = "DK"
	CountryEE Country = "EE"
	CountryES Country = "ES"
	CountryFI Country = "FI"
	CountryFR Country = "FR"
	CountryGB Country = "GB"
	CountryGR Country = "GR"
	CountryHR Country = "HR"
	CountryHU Country = "HU"
	CountryIE Country = "IE"
	CountryIS Country = "IS"
	CountryIT Country = "IT"
	CountryLI Country = "LI"
	CountryLT Country = "LT"
	CountryLU Country = "LU"
	CountryLV Country = "LV"
	CountryMC Country = "MC"
	CountryMT Country = "MT"
	CountryNL Country = "NL"
	CountryNO Country = "NO"
	CountryPL Country = "PL"
	CountryPT Country = "PT"
	CountryRO Country = "RO"
	CountrySE Country = "SE"
	CountrySI Country = "SI"
	CountrySK Country = "SK"
	CountrySM Country = "SM"
	CountryUA Country = "UA"
	CountryVA Country = "VA"

	PLN Currency = "PLN"
	EUR Currency = "EUR"
	CZK Currency = "CZK"
	HUF Currency = "HUF"
	USD Currency = "USD"
	RON Currency = "RON"
	GBP Currency = "GBP"
	CHF Currency = "CHF"

	Courier       ShippingType = 0
	ToPoint       ShippingType = 1
	Postomat      ShippingType = 2
	PackageInShop ShippingType = 3
)
